# ------------------ Compilation options ------------------------

# Location of include files for Vista
INC = -I$(VIA_INCLUDE)


# Flags for the C compiler:
CFLAGS = -O2 -Wall -shared
CC = gcc

# --------------------- Code modules ----------------------------
PROG = vtest

# List all source and object files
SRC = Aniso2d.c Aniso3d.c Bicubic.c Binarize.c Binmorph3d.c Border3d.c BorderPoint.c \
	Contrast.c CDT3d.c Canny.c ChamferDist3d.c Convolve.c \
	Curvature.c DeleteSmall.c Deriche2d.c Deriche3d.c Dist2d.c EuclideanDist3d.c \
	Filter.c GraphPrune.c GenusLee.c GreyMorph3d.c Image2Graph.c \
	ICP.c Isodata.c Label2d.c Label3d.c Lee.c Magnitude.c Median.c \
	Mask.c NNScale3d.c NonmaxSuppression.c QuickMorph.c Rotate2d.c SelectBig.c SimplePoint.c \
	Sample3d.c Scale.c Scale3d.c Smooth3d.c ShapeMoments.c Skel2d.c Skel3d.c Spline.c Thin3d.c \
	VolumesOps.c Topoclass.c VCheckPlane.c Pixel.c RotationMatrix.c
OBJ = Aniso2d.o Aniso3d.o Bicubic.o Binarize.o Binmorph3d.o Border3d.o BorderPoint.o \
	Contrast.o CDT3d.o Canny.o ChamferDist3d.o Convolve.o \
	Curvature.o DeleteSmall.o Deriche2d.o Deriche3d.o Dist2d.o EuclideanDist3d.o \
	Filter.o GraphPrune.o GenusLee.o GreyMorph3d.o Image2Graph.o \
	ICP.o Isodata.o Label2d.o Label3d.o Lee.o Magnitude.o Median.o \
	Mask.o NNScale3d.o NonmaxSuppression.o QuickMorph.o Rotate2d.o SelectBig.o SimplePoint.o \
	Sample3d.o Scale.o Scale3d.o Smooth3d.o ShapeMoments.o Skel2d.o Skel3d.o Spline.o Thin3d.o \
	VolumesOps.o Topoclass.o VCheckPlane.o Pixel.o RotationMatrix.o

# List header files
HDRS = 

# ------------------------ Rules --------------------------------
libvia.so: ${OBJ}
	ar src $@ ${OBJ}

%.o:%.c
	${CC} -c ${CFLAGS} ${INC} -c $< -o $@
