.ds Vn 1.12
.TH plaintov 1Vi "3 March 1994" "Vista Version \*(Vn"
.SH NAME
plaintov \- convert image from Vista plain file format to Vista data file
.SH SYNOPSIS
\fBplaintov\fR [\fB-\fIoption\fR ...] [\fIinfile\fR] [\fIoutfile\fR]
.SH DESCRIPTION
\fBplaintov\fP reads an image in Vista plain file format and writes is as a 
Vista data file.
.PP
Plain file format, defined in \fBVplain\fP(5Vi), allows a small image to be 
created entirely using a text editor because it represents pixel values in 
ASCII. In a Vista data file, those pixel values are encoded in binary. 
.SH "COMMAND LINE OPTIONS"
\fBplaintov\fP accepts the following options:
.IP \fB-help\fP 15n
Prints a message describing options.
.IP "\fB-in\fP \fIinfile\fP
Specifies the input file, which is in Vista plain file format.
.IP "\fB-out\fP \fIoutfile\fP"
Specifies the output file, which will be a Vista data file.
.IP "\fB-name\fP \fIname\fP"
Specifies the name to be given the converted image. Default: ``image''.
.PP
Input and output files can be specified on the command line or allowed to
default to the standard input and output streams.
.SH "SEE ALSO"
.na
.nh
.BR VImage (3Vi),
.BR Vplain (5Vi),
.BR Vfile (5Vi),
.BR Vista (7Vi)
.hy
.ad
.SH AUTHOR
Daniel Ko <ko@cs.ubc.ca>
